dependencies:
  - name: cp-helm-charts
    version: 0.1.0
    repository: https://confluentinc.github.io/cp-helm-charts/
    import-values:
      - child: cp-zookeeper
        parent: zookeeper
      - child: cp-kafka
        parent: kafka
