---

# Humio Defaults
replicas: 3
image: humio/humio-core:1.5.22

# Warning: changing this from single-user mode will disable authentication.
authenticationMethod: single-user

initImage: humio/strix:latest
initImagePullPolicy: Always

ingest:
  initialPartitionsPerNode: 4

storage:
  initialPartitionsPerNode: 4

bloomfilter:
  enabled: false
  backfillingEnabled: false

defaultUserInputRegexEngine: HUMIO

nameOverride: ""
fullnameOverride: ""

external:
  kafkaBrokers: ""
  zookeeperServers: ""

waitFor:
  kafka:
    enabled: true

service:
  type: LoadBalancer
  http_port: 8080
  es_type: ClusterIP
  es_port: 9200

resources:
  limits:
   cpu: 1
   memory: 2Gi
  requests:
   cpu: 1
   memory: 2Gi

jvm:
  xss: 2m
  xms: 256m
  xmx: 1536m

cache:
  localVolume:
    name: local-storage
    enabled: false
    hostPath: /mnt/disks
    storage:
      size: 350Gi

# Warning: cannot use pimaryStorage.type == local along with cache.localVolume.enabled == true.
primaryStorage:
  # Type can be "remote" or "local". If "remote", then use "storageClass" to define settings of the remote storage. If local,
  # use "localVolume" to define settings of the local storage.
  type: remote
  mountPath: /data/humio-data

secondaryStorage:
  type: remote
  mountPath: /data/humio-data-secondary

localVolume:
  name: local-primary-storage
  hostPath: /mnt/disks
  storage:
    size: 100Gi

compression:
  type: fast
  level: 3

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe: {}
readinessProbe: {}
storageVolume: {}
# storageClassName: custom-storage-class-name
storageClass: {}

# Dependencies
cp-helm-charts:
  cp-zookeeper:
    servers: 3
    image: confluentinc/cp-zookeeper
    imageTag: 5.2.1
    imagePullSecrets:
    heapOptions: "-Xms512M -Xmx512M"
    persistence:
      enabled: true
      dataDirSize: 10Gi
      dataLogDirSize: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 768Mi
      limits:
        cpu: 500m
        memory: 768Mi
  cp-kafka:
    brokers: 3
    image: confluentinc/cp-enterprise-kafka
    imageTag: 5.2.1
    heapOptions: "-Xms512M -Xmx512M"
    persistence:
      enabled: true
      size: 5Gi
      disksPerBroker: 1
    resources:
      requests:
        cpu: 300m
        memory: 768Mi
      limits:
        cpu: 1
        memory: 768Mi

# Ensure essential services are enabled
cp-zookeeper:
  enabled: true
cp-kafka:
  enabled: true
# Disable non-essential services
cp-schema-registry:
  enabled: false
cp-kafka-rest:
  enabled: false
cp-kafka-connect:
  enabled: false
cp-ksql-server:
  enabled: false
cp-control-center:
  enabled: false
