image: fluent/fluent-bit:1.2.2
imagePullPolicy: Always

strixImage: humio/strix:latest
strixImagePullPolicy: Always

es:
  port: 9200
  tls: false
  tls_verify: true
  autodiscovery: false

nameOverride: ""
fullnameOverride: ""

defaulInputSettings:
  memBufferLimit: 5MB

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

customFluentBitConfig:
  custom.conf: |-

nodeSelector: {}
tolerations: []
affinity: {}
