---
humio-core:
  enabled: true
  replicas: 3
  cp-helm-charts:
    cp-zookeeper:
      servers: 3
    cp-kafka:
      brokers: 3
humio-strix:
  enabled: true
  replicas: 1

global:
  sharedTokens:
    perf: {performance_tests: default}
