---
humio-core:
  enabled: true
  replicas: 3
  imagePullPolicy: Always
  cp-helm-charts:
    cp-zookeeper:
      servers: 3
    cp-kafka:
      brokers: 3

humio-strix:
  enabled: true
  replicas: 10
  imagePullPolicy: Always
  simulationOptions:
    hecSimulation:
      users: 5

humio-fluentbit:
  enabled: true
  es:
    tls: false
    autodiscovery: true

global:
  sharedTokens:
    perf: {performance-tests: default}
    fluentbit: {kubernetes: in-cluster}
    admin: {humio: default}
