---
es:
  autodiscovery: true

# humioHostname: ""

initImage: humio/strix:latest
initImagePullPolicy: Always

jobImage: humio/strix:latest
jobImagePullPolicy: Always

image: "docker.elastic.co/beats/metricbeat-oss:7.2.0"

publish:
  enabled: true
  gcs:
    bucket: ""
    directory: results
    serviceAccountSecretName: google-application-credentials

ttlSecondsAfterFinished: ""

queries: {}

resources:
  limits:
    cpu: 300m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}
tolerations: []
affinity: {}
