{{- if and (or .Values.cache.localVolume.enabled (eq .Values.primaryStorage.type "local")) .Values.cache.localVolume.createStorageClass -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-storage-admin
{{- end -}}
