{{- if or .Values.cache.localVolume.enabled (eq .Values.primaryStorage.type "local") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-storage-provisioner-node-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
{{- end -}}
