{{- if .Values.cache.localVolume.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  labels:
    app: {{ template "humio-core.name" . }}
    chart: {{ template "humio-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  useNodeNameOnly: "true"
  storageClassMap: |
    local-storage:
       hostDir: {{ .Values.cache.localVolume.hostPath }}
       mountDir: {{ .Values.cache.localVolume.hostPath }}
{{- end -}}
