apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    #"helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Release.Name }}-post-install
      initContainers:
        - name: wait-for-humio
          image: humio/strix
          command:
          - kubectl
          - wait
          - "--for=condition=Ready"
          - "pod/{{ .Release.Name }}-humio-core-0"
          - "-n"
          - {{ .Release.Namespace }}
          - "--timeout=1500s"
      containers:
      - name: set-default-partitions
        image: "humio/strix"
        command: ["/humio-balance.sh"]
        env:
          - name: HUMIO_BASE_URL
          {{- if .Values.baseUrl }}
            value: "{{ .Values.baseUrl }}"
          {{- else }}
            value: "http://{{ .Release.Name }}-humio-core-headless:8080"
          {{- end}}
          {{- if .Values.token }}
          - name: HUMIO_TOKEN
            value: {{ .Values.token }}
          {{- else -}}
            {{- if .Values.global -}}
              {{- if .Values.global.sharedTokens }}
                {{- if .Values.global.sharedTokens.admin }}
          - name: HUMIO_TOKEN
            valueFrom:
              secretKeyRef:
                name: admin-shared-token
                key: token
                {{- end -}}
              {{- end -}}
            {{- end -}}
          {{- end  }}
