apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "humio-core.fullname" . }}
  labels:
    app: {{ template "humio-core.name" . }}
    chart: {{ template "humio-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    # app.kubernetes.io/name: {{ include "humio-core.name" . }}
    # helm.sh/chart: {{ include "humio-core.chart" . }}
    # app.kubernetes.io/instance: {{ .Release.Name }}
    # app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ template "humio-core.fullname" . }}-headless
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ include "humio-core.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "humio-core.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ default "humio/humio-core:1.5.9" .Values.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: es
              containerPort: 9200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ default 300 .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: 25
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ default 300 .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: 25
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
          - mountPath: /data/humio-data
            name: humio-data-vol
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: THIS_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INGEST_QUEUE_INITIAL_PARTITIONS
              value: "50"
            - name: DEFAULT_PARTITION_COUNT
              value: "50"
            - name: HUMIO_PORT
              value: "8080"
            - name: ELASTIC_PORT
              value: "9200"
            - name: KAFKA_SERVERS
              value: {{ include "humio-core.kafka.brokers" . | quote }}
            - name: HUMIO_JVM_ARGS
              value: "-Xss2M -Xms256m -Xmx1536m -server -XX:+UseParallelOldGC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC"
            - name: ZOOKEEPER_URL
              value: {{ include "humio-core.zookeeper.servers" . | quote }}
            - name: KAFKA_MANAGED_BY_HUMIO
              value: "true"
            - name:  DEFAULT_USER_INPUT_REGEX_ENGINE
              value: "HUMIO"
            # - name: DUMP_THREADS_SECONDS
            #   value: "10"
            - name: BLOOMFILTER_BACKFILLING_ENABLED
              value: "false"
            - name: BLOOMFILTER_ENABLED
              value: "false"
            - name: EXTERNAL_URL
              value: "http://$(POD_NAME).{{ .Release.Name }}-humio-core-headless.$(POD_NAMESPACE).svc.cluster.local:8080"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: humio-data-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storageVolume.size | default "10Gi" }}
