apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "humio-core.fullname" . }}
  labels:
    app: {{ template "humio-core.name" . }}
    chart: {{ template "humio-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "humio-core.fullname" . }}-headless
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "humio-core.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "humio-core.name" . }}
        release: {{ .Release.Name }}
        humio-parser: {{ default "kv" .Values.humioParser }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Release.Name }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.waitFor.kafka.enabled }}
      {{- if eq .Values.external.kafkaBrokers "" }}
      initContainers:
        - name: wait-for-kafka
          image: humio/strix
          command:
          - kubectl
          - wait
          - "--for=condition=Ready"
          - "pod/{{ .Release.Name }}-cp-kafka-{{ sub .Values.kafka.brokers 1 }}"
          - "-n"
          - {{ .Release.Namespace }}
          - "--timeout=1500s"
      {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ default "humio/humio-core:1.6.0" .Values.image }}
          command: ["/bin/sh"]
          args: ["-c", "export BOOTSTRAP_HOST_ID=$((${POD_NAME##*-} + 1)) && bash /app/humio/run.sh"]
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: es
              containerPort: 9200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ default 30 .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ default 30 .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
          - mountPath: /data/humio-data
            name: humio-data-vol
        {{- if .Values.cache.localVolume.enabled }}
          - name: local-vol
            mountPath: /data-local
        {{- end }}
          env:
          {{- if .Values.cache.localVolume.enabled }}
            - name: CACHE_STORAGE_DIRECTORY
              value: "/data-local"
            - name: CACHE_STORAGE_PERCENTAGE
              value: "90"
          {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: THIS_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INGEST_QUEUE_INITIAL_PARTITIONS
              value: {{ mul .Values.replicas .Values.ingest.initialPartitionsPerNode | quote }}
            - name: DEFAULT_PARTITION_COUNT
              value: {{ mul .Values.replicas .Values.storage.initialPartitionsPerNode | quote }}
            - name: COMPRESSION_TYPE
              value: {{ .Values.compression.type | quote }}
            - name: COMPRESSION_LEVEL
              value: {{ .Values.compression.level | quote }}
            - name: HUMIO_PORT
              value: "8080"
            - name: ELASTIC_PORT
              value: "9200"
            - name: KAFKA_SERVERS
              value: {{ include "humio-core.kafka.brokers" . | quote }}
            - name: HUMIO_JVM_ARGS
              value: "-Xss{{ default "2m" .Values.jvm.xss }} -Xms{{ default "256m" .Values.jvm.xms }} -Xmx{{ default "1536m" .Values.jvm.xmx }} -server -XX:+UseParallelOldGC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC"
            - name: ZOOKEEPER_URL
              value: {{ include "humio-core.zookeeper.servers" . | quote }}
            - name: KAFKA_MANAGED_BY_HUMIO
              value: "true"
            - name: DEFAULT_USER_INPUT_REGEX_ENGINE
              value: {{ .Values.defaultUserInputRegexEngine | quote }}
            - name: BLOOMFILTER_BACKFILLING_ENABLED
              value: {{ .Values.bloomfilter.backfillingEnabled | quote }}
            - name: BLOOMFILTER_ENABLED
              value: {{ .Values.bloomfilter.enabled | quote }}
            - name: EXTERNAL_URL
              value: "http://$(POD_NAME).{{ .Release.Name }}-humio-core-headless.$(POD_NAMESPACE).svc.cluster.local:8080"
            {{- if ne .Values.authenticationMethod "" }}
            - name: AUTHENTICATION_METHOD
              value: {{ default "single-user" .Values.authenticationMethod | quote }}
            {{- end }}
            - name: SINGLE_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: developer-user-password
                  key: password
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: humio-data-vol
    spec:
      accessModes:
        - ReadWriteOnce
    {{- if .Values.storageClass }}
      storageClassName: "custom-storage-class"
    {{- else if .Values.storageClassName }}
      storageClassName: "{{ .Values.storageClassName }}"
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.storageVolume.size | default "10Gi" }}
{{- if .Values.cache.localVolume.enabled }}
  - metadata:
      name: local-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: {{ .Values.cache.localVolume.storage.size }}
{{- end }}
