apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "humio-strix.fullname" . }}
  labels:
{{ include "humio-strix.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "humio-strix.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "humio-strix.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: PERF_USERS
              value: {{ default "10" .Values.testOptions.users | quote }}
            - name: PERF_GB_DAY
              value: {{ default "2000" .Values.testOptions.gbPerDay | quote }}
            - name: PERF_DATASOURCES
              value: {{ default "5" .Values.testOptions.datasources | quote }}
            - name: PERF_BULK_SIZE
              value: {{ default "5" .Values.testOptions.bulkSize | quote }}
            {{- if .Values.token }}
            - name: HUMIO_TOKEN
              value: {{ .Values.token }}
            {{- else -}}
              {{- if .Values.global -}}
                {{- if .Values.global.sharedTokens }}
                  {{- if .Values.global.sharedTokens.perf }}
            - name: HUMIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: perf-shared-token
                  key: token
                  {{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end  }}
            - name: HUMIO_BASE_URL
              value: {{ default "http://humio-humio-core-http:8080/api/v1/ingest/elastic-bulk" .Values.baseUrl }}
            - name: PERF_SIMULATION
              value: {{ default "FixedRateIngestSimulation" .Values.testOptions.simulation }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
