apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "humio.fullname" . }}
  labels:
    app: {{ template "humio.name" . }}
    chart: {{ template "humio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    # app.kubernetes.io/name: {{ include "humio.name" . }}
    # helm.sh/chart: {{ include "humio.chart" . }}
    # app.kubernetes.io/instance: {{ .Release.Name }}
    # app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "humio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "humio.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: es
              containerPort: 9200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 25
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 25
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
          - mountPath: /data/humio-data
            name: humio-data-vol 
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: THIS_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HUMIO_PORT
              value: "8080"
            - name: ELASTIC_PORT
              value: "9200"
            - name: KAFKA_SERVERS
              value: "humio-kafka-cp-kafka-0.humio-kafka-cp-kafka-headless:9092,humio-kafka-cp-kafka-1.humio-kafka-cp-kafka-headless:9092,humio-kafka-cp-kafka-2.humio-kafka-cp-kafka-headless:9092"
            - name: HUMIO_JVM_ARGS
              value: {{ .Values.jvm_args }}
            - name: ZOOKEEPER_URL
              value: "humio-kafka-cp-zookeeper-0.humio-kafka-cp-zookeeper-headless:2181,humio-kafka-cp-zookeeper-1.humio-kafka-cp-zookeeper-headless:2181,humio-kafka-oss-cp-zookeeper-2.humio-kafka-oss-cp-zookeeper-headless:2181"
            - name: KAFKA_MANAGED_BY_HUMIO
              value: "true"
            - name: EXTERNAL_URL
              value: "http://$(THIS_POD_IP):8080"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: humio-data-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 48Gi
      storageClassName: local-storage
