apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "humio.fullname" . }}
  labels:
    app: {{ template "humio.name" . }}
    chart: {{ template "humio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    # app.kubernetes.io/name: {{ include "humio.name" . }}
    # helm.sh/chart: {{ include "humio.chart" . }}
    # app.kubernetes.io/instance: {{ .Release.Name }}
    # app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  # podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ include "humio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "humio.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: es
              containerPort: 9200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15 
            timeoutSeconds: 25
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15 
            timeoutSeconds: 25
            periodSeconds: 5 
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
          - mountPath: /data/humio-data
            name: humio-data-vol 
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: THIS_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INGEST_QUEUE_INITIAL_PARTITIONS
              value: "72"
            - name: DEFAULT_PARTITION_COUNT
              value: "72"
            - name: HUMIO_PORT
              value: "8080"
            - name: ELASTIC_PORT
              value: "9200"
            - name: KAFKA_SERVERS
              value: "kafka-cp-kafka-0.kafka-cp-kafka-headless:9092,kafka-cp-kafka-1.kafka-cp-kafka-headless:9092,kafka-cp-kafka-2.kafka-cp-kafka-headless:9092,kafka-cp-kafka-3.kafka-cp-kafka-headless:9092,kafka-cp-kafka-4.kafka-cp-kafka-headless:9092,kafka-cp-kafka-5.kafka-cp-kafka-headless:9092,kafka-cp-kafka-6.kafka-cp-kafka-headless:9092,kafka-cp-kafka-7.kafka-cp-kafka-headless:9092,kafka-cp-kafka-8.kafka-cp-kafka-headless:9092"
            - name: HUMIO_JVM_ARGS
              value: "-Xss2M -Xms4G -Xmx64G -server -XX:+UseParallelOldGC "
            - name: ZOOKEEPER_URL
              value: "kafka-cp-zookeeper-0.kafka-cp-zookeeper-headless:2181,kafka-cp-zookeeper-1.kafka-cp-zookeeper-headless:2181,kafka-cp-zookeeper-2.kafka-cp-zookeeper-headless:2181,kafka-cp-zookeeper-3.kafka-cp-zookeeper-headless:2181,kafka-cp-zookeeper-4.kafka-cp-zookeeper-headless:2181"
            - name: KAFKA_MANAGED_BY_HUMIO
              value: "true"
            - name: EXTERNAL_URL
              value: "http://$(THIS_POD_IP):8080"
            - name: GITHUB_USER_SETTING
              value: "hello8675309:hello8675309humio"
            - name: GITHUB_USER
              value: "hello8675309:hello8675309humio"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: humio-data-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Gi
      # storageClassName: faster
